### PR TITLE
Fix #941: fix undeclared identifier error of S_IWUSR

### LINKED ISSUE #941: 4.1.0 build fails on FreeBSD: mz_strm_os_posix.c:93:42: error: use of undeclared identifier 'S_IWUSR'
```
[ 59% 16/22] /usr/bin/cc -DHAVE_BZIP2 -DHAVE_ICONV -DHAVE_INTTYPES_H -DHAVE_LZMA -DHAVE_PKCRYPT -DHAVE_STDINT_H -DHAVE_WZAES -DHAVE_ZLIB -DHAVE_ZSTD -DLZMA_API_STATIC -DMZ_EXPORTS -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_LARGEFILE64_SOURCE -D_POSIX_C_SOURCE=200809L -D__USE_LARGEFILE64 -I/usr/local/include -I/tmp/work/usr/ports/archivers/minizip-ng/work/minizip-ng-4.1.0 -I/tmp/work/usr/ports/archivers/minizip-ng/work/minizip-ng-4.1.0/compat -I/tmp/work/usr/ports/archivers/minizip-ng/work/.build -O2 -pipe -march=core2  -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing -O2 -pipe -march=core2  -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing  -DNDEBUG -std=gnu99 -fPIC -MD -MT CMakeFiles/minizip-ng.dir/mz_strm_os_posix.c.o -MF CMakeFiles/minizip-ng.dir/mz_strm_os_posix.c.o.d -o CMakeFiles/minizip-ng.dir/mz_strm_os_posix.c.o -c /tmp/work/usr/ports/archivers/minizip-ng/work/minizip-ng-4.1.0/mz_strm_os_posix.c
FAILED: [code=1] CMakeFiles/minizip-ng.dir/mz_strm_os_posix.c.o
/usr/bin/cc -DHAVE_BZIP2 -DHAVE_ICONV -DHAVE_INTTYPES_H -DHAVE_LZMA -DHAVE_PKCRYPT -DHAVE_STDINT_H -DHAVE_WZAES -DHAVE_ZLIB -DHAVE_ZSTD -DLZMA_API_STATIC -DMZ_EXPORTS -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_LARGEFILE64_SOURCE -D_POSIX_C_SOURCE=200809L -D__USE_LARGEFILE64 -I/usr/local/include -I/tmp/work/usr/ports/archivers/minizip-ng/work/minizip-ng-4.1.0 -I/tmp/work/usr/ports/archivers/minizip-ng/work/minizip-ng-4.1.0/compat -I/tmp/work/usr/ports/archivers/minizip-ng/work/.build -O2 -pipe -march=core2  -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing -O2 -pipe -march=core2  -DLIBICONV_PLUG -fstack-protector-strong -fno-strict-aliasing  -DNDEBUG -std=gnu99 -fPIC -MD -MT CMakeFiles/minizip-ng.dir/mz_strm_os_posix.c.o -MF CMakeFiles/minizip-ng.dir/mz_strm_os_posix.c.o.d -o CMakeFiles/minizip-ng.dir/mz_strm_os_posix.c.o -c /tmp/work/usr/ports/archivers/minizip-ng/work/minizip-ng-4.1.0/mz_strm_os_posix.c
/tmp/work/usr/ports/archivers/minizip-ng/work/minizip-ng-4.1.0/mz_strm_os_posix.c:93:32: error: use of undeclared identifier 'S_IRUSR'
   93 |     fd = open(path, mode_open, S_IRUSR | S_IWUSR | S_IRGRP);
      |                                ^
/tmp/work/usr/ports/archivers/minizip-ng/work/minizip-ng-4.1.0/mz_strm_os_posix.c:93:42: error: use of undeclared identifier 'S_IWUSR'
   93 |     fd = open(path, mode_open, S_IRUSR | S_IWUSR | S_IRGRP);
      |                                          ^
/tmp/work/usr/ports/archivers/minizip-ng/work/minizip-ng-4.1.0/mz_strm_os_posix.c:93:52: error: use of undeclared identifier 'S_IRGRP'
   93 |     fd = open(path, mode_open, S_IRUSR | S_IWUSR | S_IRGRP);
      |                                                    ^
3 errors generated.
```

Fastfix:
```
--- mz_strm_os_posix.c.orig     2026-01-21 21:52:59 UTC
+++ mz_strm_os_posix.c
@@ -21,6 +21,9 @@
 #include <errno.h>
 #include <unistd.h>  // open, close, ...
 #include <fcntl.h>   // O_NOFOLLOW, ...
+#ifdef __FreeBSD__
+#include <sys/stat.h>
+#endif
 
 /***************************************************************************/
 
```

### PR DESCRIPTION
**Pull request by apocelipes**
Fixes #941. POSIX defines these macros in `<sys/stat.h>`.

### CODE REVIEW

File: mz_strm_os_posix.c [hunk 1]
```diff
@@ -19,8 +19,9 @@
 
 #include <stdio.h> /* fopen, fread.. */
 #include <errno.h>
-#include <unistd.h>  // open, close, ...
-#include <fcntl.h>   // O_NOFOLLOW, ...
+#include <sys/stat.h>  // S_IWUSR, ...
```
Comment (nmoinvaz) [inline mz_strm_os_posix.c]: Can you use multi line comments and align also the fopen/fread one? Thanks!

Comment (nmoinvaz) [inline mz_strm_os_posix.c]: Will Windows still compile with these includes?

Comment (apocelipes) [reply mz_strm_os_posix.c]: Windows won't use this. They use `mz_strm_os_win32.c`.

Comment (apocelipes) [reply mz_strm_os_posix.c]: The CI failure seems like unrelated:
```console
CMake Error at CMakeLists.txt:741 (install):
  install TARGETS given target "zlib" which is an alias.
```

Comment (apocelipes) [reply mz_strm_os_posix.c]: Done.

**Comment by nmoinvaz** [comment]
When I ran the workflow, it looks like there is a linter issue that clang-format doesn't like. Can you also rebase, it should fix the windows install error.

**Comment by apocelipes** [comment]
> When I ran the workflow, it looks like there is a linter issue that clang-format doesn't like. Can you also rebase, it should fix the windows install error.

Done. The code uses the format suggested by clang-format.

**Comment by apocelipes** [comment]
Windows CI still fails, but the error message has changed:
```console
CMake Error at CMakeLists.txt:749 (install):
  install TARGETS given target "zlibstatic-ng" which does not exist.
```

Maybe you could merge this first and then fix Windows, since the error isn't related to this PR's commit.

**Review by nmoinvaz — APPROVED** [review]
